### ISSUE TITLE
low prio: Multiple venues per business

### ISSUE THREAD

**Issue by rcoppa** [DisruptSydney/Into#3] opened 2015-03-09 03:42 UTC
In progress

**Comment by rcoppa** [comment] 2015-03-11 07:09
Looks good.

When the add business button is pressed the new form should display on the existing page in the middle column under 'payment', not on a separate page.

**Comment by rcoppa** [comment] 2015-03-11 07:10
Please confirm the design file used. Should be 150228_INTO_Website.ai

**Comment by rcoppa** [comment] 2015-03-11 07:14
Each business venue should have an indicator if its not approved yet 'Pending Approval'

**Comment by multidimensionro** [comment] 2015-03-11 16:05
Hi Reuben,

That is the AI we used. We have done the fixes as requested on staging.

Best regards

**Comment by MaximilianArasin** [comment] 2015-03-11 21:40
Hi,
just had a test run. Feedback: intended design is applied...looking good. But User still gets navigated to business application screen once "add business" is clicked. Also Select parent business does not work.

cheers

**Comment by MaximilianArasin** [comment] 2015-03-11 21:40
Hi,
just had a test run. Feedback: intended design is applied...looking good. But User still gets navigated to business application screen once "add business" is clicked. Also Select parent business does not work.

cheers

**Comment by rcoppa** [comment] 2015-03-12 05:01
Looks great! 
![screen shot 2015-03-12 at 4 01 16 pm](https://cloud.githubusercontent.com/assets/1256325/6612481/1592eef2-c8d1-11e4-86f8-92daff99ffb6.png)
The tick that indicates payment should appear when the business venue is selected, as well as unselected.

When the business / venue is unapproved and grey it should so in brackets (pending approval) also.

**Comment by rcoppa** [comment] 2015-03-12 05:05
The label should be changed from "Update" to "Apply"

**Comment by MaximilianArasin** [comment] 2015-03-17 19:42
@rcoppa @multidimensionro 
please find my latest comment from my email to Reuben from yesterday:
Business Login – multiple venues

- Shows approval pending even if business is approved in the backend. Please double check the different states of the fields as discussed. (grey, approval pending, gold,blue,ticks)
- Please change pending approval to approval pending.
- Add business – user still jumps to the business application screen. Please allow add field under the account tab in the business partner section as discussed.
- Master business account (parent business) - Please allow set up for a master account that has only account info but no payment and no offer. In this account under payment and my offer it should just say: This is your master account. Please add business(es) to create offer(s). f you have any questions or comments please contact us via partners@getintoapp.com - we are always here to listen and help!


![screen shot 2015-03-16 at 3 26 20 pm](https://cloud.githubusercontent.com/assets/11382000/6695978/d09deb12-cce5-11e4-9b4c-8340ccf83b9d.png)
![screen shot 2015-03-16 at 3 26 43 pm](https://cloud.githubusercontent.com/assets/11382000/6695980/d3d0ad06-cce5-11e4-83bc-1f4b513ed685.png)


Any updates on this please? When will this be seamlessly working and moved from staging to live? Would be great if you could send the current link so I can test again.

Thx and cheers
Max

**Comment by multidimensionro** [comment] 2015-03-18 07:45
Hi @MaximilianArasin, @rcoppa,

Concerning the above everything was fixed on staging http://into.disruptdevs.com/:

1) Approved businesses are marked as "pending payment". Non-approved business are marked as "pending review". For business pending review only changes to the business submission are accepted. Payment and My Offer tabs are disabled. For businesses under "pending payment" only the My Offer tab is disabled.
2) The pending wording has been changed.
3) Add business is now included into the same design as part of a new business setup.
4) This is not possible. The master account must have an offer associated to make use of the parent business setup, otherwise payment data can't be handled.

Best regards,
Darius-Sorin Bodescu

**Comment by MaximilianArasin** [comment] 2015-03-18 09:32
Hi @rcoppa @multidimensionro 

thanks for the update. Looks good. Just from a first quick test please find the following screenshot below:
![screenshot_08](https://cloud.githubusercontent.com/assets/11382000/6705824/aff9331c-cd58-11e4-9c69-9a0d4137dde6.jpg)
After adding a business both business fields are gray (indicating that no business is selected) ... I think the one that is displayed on the left should be blue instead of grey by default to indicate that it is selected. This works if I click on the field but not by default if I add a business. Makes sense?

Concerning 4) - well, okay then. Thx for the clarification.

I will do some further testing ... but looks like we can move it to live soon once Reuben and you are happy with it as well.

Cheers
Max

**Comment by rcoppa** [comment] 2015-03-23 07:40
Hey @multidimensionro can we now safely move this issue to live?

**Comment by multidimensionro** [comment] 2015-03-23 07:53
Hi @rcoppa 

Latest issues have been handled on staging. Please review and notify us when to push live. From our point of view it works properly.

Best regards,
Darius-Sorin Bodescu

**Comment by MaximilianArasin** [comment] 2015-03-23 10:48
Hi @rcoppa  @multidimensionro 
would be great to push this life once different scenarios are tested properly(e.g. does payment work if businesses are added or deleted during the process, login with one email for multiple businesses, etc).

The app will be approved this week and we need to sign businesses ... so this would be appreciated.
Thanks a lot guys
cheers
Max

**Comment by multidimensionro** [comment] 2015-04-08 14:34
@MaximilianArasin @rcoppa 
This has been moved live and it is fully functional.

**Comment by MaximilianArasin** [comment] 2015-04-09 08:45
@multidimensionro here comes the issues we had after testing this:

1. Lucas test experience: I reset the password for my LF hotel account and after I entered my email address and hit reset password it took me back to this screen – I think it would be smarter to take the user back to the homepage – thoughts? Once I went to my email and got the password changed it was all very easy. Max test experience: I did not change the password in the 2nd business I added and after I loged out I couldn't login again. I also couldn't login to the admin because I used the same email address and it must have killed it somehow.
--> my idea is to just allow the user to set a password for the very first business and when business added the password field is hidden for those added. I think it causes to many problems and confuses the user if they got taken to another screen. The idea was to have it all on one screen but it doesn't seem to work properly. Happy for your ideas on this.

![screen shot 2015-04-09 at 1 37 26 pm](https://cloud.githubusercontent.com/assets/11382000/7063256/68eaeaac-dea5-11e4-825f-ecaa88e3e7a1.png)

**Comment by MaximilianArasin** [comment] 2015-04-09 08:51
2. why does it still show the 45 day free trial? 
![screen shot 2015-04-09 at 1 44 05 pm](https://cloud.githubusercontent.com/assets/11382000/7063321/02e5b1be-dea6-11e4-8b2f-36f6507319d6.png)

question here: does the quantity push work properly with fast spring? can you set up multiple venues and then only do one payment for them all as intended ? maybe we have to do some more testing here. If you need me to get more info from fast spring, please let me know.

**Comment by MaximilianArasin** [comment] 2015-04-09 08:55
3. system will not allow voucher codes to work – I tried 2 & 6 months codes:
![screen shot 2015-04-09 at 1 46 05 pm](https://cloud.githubusercontent.com/assets/11382000/7063384/83231fa6-dea6-11e4-819a-4c94da3052c3.png)

![screen shot 2015-04-09 at 1 45 29 pm](https://cloud.githubusercontent.com/assets/11382000/7063400/90a810fa-dea6-11e4-8a33-c504d170466a.png)

Question: Is there any relation between us pushing quantities to fast spring and the discount voucher on fast spring (that I set up on fast spring for our users to get some more month for free)?

**Comment by MaximilianArasin** [comment] 2015-04-09 09:00
D. tester experience: screen gives no indication on how to get back to your offers or homepage – when I went back to to the open screen of my session it said payment wasn’t done – I knew personally that I had to log out and back in for it to work but how will a user know this?
![screen shot 2015-04-09 at 1 46 49 pm](https://cloud.githubusercontent.com/assets/11382000/7063464/4a3415a0-dea7-11e4-9c08-78a9276b5e8f.png)

Question: I think here we should add guiding information and maybe a link back to the business section via fast springs site. I will try to find out if they can do this for us.

**Comment by MaximilianArasin** [comment] 2015-04-09 09:04
E. User feedback: payment was only successful for the first account – I was never offered to buy multiple subscriptions – will the user have to enter credit card info every time??? 

Question is related to B. we have to allow the user to make one payment for all added businesses. That was the idea of this multiple business update. Can we please do some more testing and improvement on the quantity push to fast spring? The user should only have to do one payment for all added businesses. By of course allowing the user to add a business at a later stage and do the payment separately.
Happy for your input.

![screen shot 2015-04-09 at 1 48 32 pm](https://cloud.githubusercontent.com/assets/11382000/7063584/3970d630-dea8-11e4-824c-b2ca0aeed1e8.png)

**Comment by MaximilianArasin** [comment] 2015-04-09 10:12
@multidimensionro  as mentioned above my admin login doesn't work anymore since I did not enter a new password for a business I added in the business partner section using my details: max@getintoapp.com password Deutschland123

would be great if you could activate my admin access please.

thx

**Comment by multidimensionro** [comment] 2015-04-09 15:28
Hi @MaximilianArasin,

A. We left the password change field only on the primary business tab. from the http://getintoapp.com/index/form

B. The product configuration from fast spring is with the 45 free trial.

B QA : When the payment is done the first business that will be update if is needed will be the main business.
Then it will validate the payment for the associated businesses in ASC order of there id's.

C. This problem is from fast spring. The problem could be caused by the free trial period product(if the product is free the fast spring is not allowing a customer to apply a discount voucher).

D. We can't redirect the user from fast spring back to the website. We are using target="_blank" on the fast spring link to open in to another page.
-There is an ajax verification every 10 seconds if there where was a payment done.
-After making the order, fast spring is sending on complete order some parameters to a function in website. From there we are making businesses payment valid based on quantity and order.

E. The quantity is based on the businesses approved and with no payment done. If the business in pending approval it will not be added to the quantity.

Best regards,
Darius-Sorin Bodescu

**Comment by multidimensionro** [comment] 2015-06-18 08:17
Hi @MaximilianArasin,

I think this can be closed.

Best regards,
Darius-Sorin Bodescu

**Closed** 2015-06-18 08:21 UTC
Labels: backend, enhancement
